/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer extends org.jooq.impl.TableImpl<Database.JooqGenerated.tables.records.CustomerRecord> {

	private static final long serialVersionUID = 1438246957;

	/**
	 * The reference instance of <code>Customer</code>
	 */
	public static final Database.JooqGenerated.tables.Customer CUSTOMER = new Database.JooqGenerated.tables.Customer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<Database.JooqGenerated.tables.records.CustomerRecord> getRecordType() {
		return Database.JooqGenerated.tables.records.CustomerRecord.class;
	}

	/**
	 * The column <code>Customer.UID</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.Integer> UID = createField("UID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Customer.Name</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.String> NAME = createField("Name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Customer.Salutation</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.String> SALUTATION = createField("Salutation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Customer.Username</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.String> USERNAME = createField("Username", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Customer.Birthday</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.Integer> BIRTHDAY = createField("Birthday", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Customer.Mobile</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.Integer> MOBILE = createField("Mobile", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Customer.Email</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.String> EMAIL = createField("Email", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Customer.Password</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.CustomerRecord, java.lang.String> PASSWORD = createField("Password", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>Customer</code> table reference
	 */
	public Customer() {
		this("Customer", null);
	}

	/**
	 * Create an aliased <code>Customer</code> table reference
	 */
	public Customer(java.lang.String alias) {
		this(alias, Database.JooqGenerated.tables.Customer.CUSTOMER);
	}

	private Customer(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.CustomerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Customer(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.CustomerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.JooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<Database.JooqGenerated.tables.records.CustomerRecord> getPrimaryKey() {
		return Database.JooqGenerated.Keys.PK_CUSTOMER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<Database.JooqGenerated.tables.records.CustomerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<Database.JooqGenerated.tables.records.CustomerRecord>>asList(Database.JooqGenerated.Keys.PK_CUSTOMER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Database.JooqGenerated.tables.Customer as(java.lang.String alias) {
		return new Database.JooqGenerated.tables.Customer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Database.JooqGenerated.tables.Customer rename(java.lang.String name) {
		return new Database.JooqGenerated.tables.Customer(name, null);
	}
}
