/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movie extends org.jooq.impl.TableImpl<Database.JooqGenerated.tables.records.MovieRecord> {

	private static final long serialVersionUID = -2043501920;

	/**
	 * The reference instance of <code>Movie</code>
	 */
	public static final Database.JooqGenerated.tables.Movie MOVIE = new Database.JooqGenerated.tables.Movie();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<Database.JooqGenerated.tables.records.MovieRecord> getRecordType() {
		return Database.JooqGenerated.tables.records.MovieRecord.class;
	}

	/**
	 * The column <code>Movie.MID</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.Integer> MID = createField("MID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_name</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_NAME = createField("Movie_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_type</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_TYPE = createField("Movie_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_date</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.Integer> MOVIE_DATE = createField("Movie_date", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_class</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_CLASS = createField("Movie_class", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_lang</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_LANG = createField("Movie_lang", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_length</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.Integer> MOVIE_LENGTH = createField("Movie_length", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_director</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_DIRECTOR = createField("Movie_director", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_cast</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_CAST = createField("Movie_cast", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Movie.Movie_location</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.MovieRecord, java.lang.String> MOVIE_LOCATION = createField("Movie_location", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>Movie</code> table reference
	 */
	public Movie() {
		this("Movie", null);
	}

	/**
	 * Create an aliased <code>Movie</code> table reference
	 */
	public Movie(java.lang.String alias) {
		this(alias, Database.JooqGenerated.tables.Movie.MOVIE);
	}

	private Movie(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.MovieRecord> aliased) {
		this(alias, aliased, null);
	}

	private Movie(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.MovieRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.JooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<Database.JooqGenerated.tables.records.MovieRecord> getPrimaryKey() {
		return Database.JooqGenerated.Keys.PK_MOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<Database.JooqGenerated.tables.records.MovieRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<Database.JooqGenerated.tables.records.MovieRecord>>asList(Database.JooqGenerated.Keys.PK_MOVIE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Database.JooqGenerated.tables.Movie as(java.lang.String alias) {
		return new Database.JooqGenerated.tables.Movie(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Database.JooqGenerated.tables.Movie rename(java.lang.String name) {
		return new Database.JooqGenerated.tables.Movie(name, null);
	}
}
