/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence extends org.jooq.impl.TableImpl<Database.JooqGenerated.tables.records.SqliteSequenceRecord> {

	private static final long serialVersionUID = -1803443152;

	/**
	 * The reference instance of <code>sqlite_sequence</code>
	 */
	public static final Database.JooqGenerated.tables.SqliteSequence SQLITE_SEQUENCE = new Database.JooqGenerated.tables.SqliteSequence();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<Database.JooqGenerated.tables.records.SqliteSequenceRecord> getRecordType() {
		return Database.JooqGenerated.tables.records.SqliteSequenceRecord.class;
	}

	/**
	 * The column <code>sqlite_sequence.name</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.SqliteSequenceRecord, java.lang.Object> NAME = createField("name", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * The column <code>sqlite_sequence.seq</code>.
	 */
	public final org.jooq.TableField<Database.JooqGenerated.tables.records.SqliteSequenceRecord, java.lang.Object> SEQ = createField("seq", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * Create a <code>sqlite_sequence</code> table reference
	 */
	public SqliteSequence() {
		this("sqlite_sequence", null);
	}

	/**
	 * Create an aliased <code>sqlite_sequence</code> table reference
	 */
	public SqliteSequence(java.lang.String alias) {
		this(alias, Database.JooqGenerated.tables.SqliteSequence.SQLITE_SEQUENCE);
	}

	private SqliteSequence(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.SqliteSequenceRecord> aliased) {
		this(alias, aliased, null);
	}

	private SqliteSequence(java.lang.String alias, org.jooq.Table<Database.JooqGenerated.tables.records.SqliteSequenceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.JooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Database.JooqGenerated.tables.SqliteSequence as(java.lang.String alias) {
		return new Database.JooqGenerated.tables.SqliteSequence(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Database.JooqGenerated.tables.SqliteSequence rename(java.lang.String name) {
		return new Database.JooqGenerated.tables.SqliteSequence(name, null);
	}
}
