/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated;

/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<Database.JooqGenerated.tables.records.CustomerRecord> PK_CUSTOMER = UniqueKeys0.PK_CUSTOMER;
	public static final org.jooq.UniqueKey<Database.JooqGenerated.tables.records.MovieRecord> PK_MOVIE = UniqueKeys0.PK_MOVIE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<Database.JooqGenerated.tables.records.CustomerRecord> PK_CUSTOMER = createUniqueKey(Database.JooqGenerated.tables.Customer.CUSTOMER, Database.JooqGenerated.tables.Customer.CUSTOMER.UID);
		public static final org.jooq.UniqueKey<Database.JooqGenerated.tables.records.MovieRecord> PK_MOVIE = createUniqueKey(Database.JooqGenerated.tables.Movie.MOVIE, Database.JooqGenerated.tables.Movie.MOVIE.MID);
	}
}
