/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated;

/**
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Customer
	 */
	public static final Database.JooqGenerated.tables.Customer CUSTOMER = Database.JooqGenerated.tables.Customer.CUSTOMER;

	/**
	 * The table Movie
	 */
	public static final Database.JooqGenerated.tables.Movie MOVIE = Database.JooqGenerated.tables.Movie.MOVIE;

	/**
	 * The table sqlite_sequence
	 */
	public static final Database.JooqGenerated.tables.SqliteSequence SQLITE_SEQUENCE = Database.JooqGenerated.tables.SqliteSequence.SQLITE_SEQUENCE;
}
