/*
 * This file is generated by jOOQ.
*/
package Database.JooqGenerated;


import Database.JooqGenerated.tables.Customer;
import Database.JooqGenerated.tables.Movie;
import Database.JooqGenerated.tables.SqliteSequence;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Customer</code>.
     */
    public static final Customer CUSTOMER = Database.JooqGenerated.tables.Customer.CUSTOMER;

    /**
     * The table <code>Movie</code>.
     */
    public static final Movie MOVIE = Database.JooqGenerated.tables.Movie.MOVIE;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = Database.JooqGenerated.tables.SqliteSequence.SQLITE_SEQUENCE;
}
