/**
 * This class is generated by jOOQ
 */
package Database.JooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends org.jooq.impl.UpdatableRecordImpl<Database.JooqGenerated.tables.records.CustomerRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -558998120;

	/**
	 * Setter for <code>Customer.UID</code>.
	 */
	public void setUid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Customer.UID</code>.
	 */
	public java.lang.Integer getUid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Customer.Name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Customer.Name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Customer.Salutation</code>.
	 */
	public void setSalutation(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Customer.Salutation</code>.
	 */
	public java.lang.String getSalutation() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>Customer.Username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Customer.Username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>Customer.Birthday</code>.
	 */
	public void setBirthday(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Customer.Birthday</code>.
	 */
	public java.lang.Integer getBirthday() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>Customer.Mobile</code>.
	 */
	public void setMobile(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Customer.Mobile</code>.
	 */
	public java.lang.Integer getMobile() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>Customer.Email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Customer.Email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>Customer.Password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>Customer.Password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.SALUTATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.BIRTHDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return Database.JooqGenerated.tables.Customer.CUSTOMER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSalutation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getBirthday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value1(java.lang.Integer value) {
		setUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value3(java.lang.String value) {
		setSalutation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value4(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value5(java.lang.Integer value) {
		setBirthday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value6(java.lang.Integer value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value7(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord value8(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerRecord
	 */
	public CustomerRecord() {
		super(Database.JooqGenerated.tables.Customer.CUSTOMER);
	}

	/**
	 * Create a detached, initialised CustomerRecord
	 */
	public CustomerRecord(java.lang.Integer uid, java.lang.String name, java.lang.String salutation, java.lang.String username, java.lang.Integer birthday, java.lang.Integer mobile, java.lang.String email, java.lang.String password) {
		super(Database.JooqGenerated.tables.Customer.CUSTOMER);

		setValue(0, uid);
		setValue(1, name);
		setValue(2, salutation);
		setValue(3, username);
		setValue(4, birthday);
		setValue(5, mobile);
		setValue(6, email);
		setValue(7, password);
	}
}
