CREATE TABLE `Customer` (
	`UID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Salutation`	TEXT NOT NULL,
	`Username`	TEXT NOT NULL,
	`Mobile`	INTEGER NOT NULL,
	`Email`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL,
	`Birthday`	TEXT NOT NULL
);
CREATE TABLE `Movie` (
	`MID`	INTEGER NOT NULL,
	`Movie_name`	TEXT NOT NULL,
	`Movie_type`	TEXT NOT NULL,
	`Movie_date`	TEXT NOT NULL,
	`Movie_class`	TEXT NOT NULL,
	`Movie_lang`	TEXT NOT NULL,
	`Movie_length`	INTEGER NOT NULL,
	`Movie_director`	TEXT NOT NULL,
	`Movie_cast`	TEXT NOT NULL,
	`Movie_location`	TEXT NOT NULL
);
CREATE TABLE `Staff` (
	`SID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL
);
CREATE TABLE `transactions` (
	`TID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`StaffId`	INTEGER NOT NULL,
	`MemberId`	INTEGER NOT NULL,
	FOREIGN KEY(`StaffId`) REFERENCES `Staff`(`SID`),
	FOREIGN KEY(`MemberId`) REFERENCES `Customer`(`UID`)
);
