/*
 * This file is generated by jOOQ.
*/
package org.comp3046.it9.Database.JooqGenerated;


import org.comp3046.it9.Database.JooqGenerated.tables.Customer;
import org.comp3046.it9.Database.JooqGenerated.tables.Staff;
import org.comp3046.it9.Database.JooqGenerated.tables.Transactions;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code></code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Integer> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<Record, Integer> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
    public static final Identity<Record, Integer> IDENTITY_TRANSACTIONS = Identities0.IDENTITY_TRANSACTIONS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> PK_CUSTOMER = UniqueKeys0.PK_CUSTOMER;
    public static final UniqueKey<Record> PK_STAFF = UniqueKeys0.PK_STAFF;
    public static final UniqueKey<Record> PK_TRANSACTIONS = UniqueKeys0.PK_TRANSACTIONS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> FK_TRANSACTIONS_STAFF_1 = ForeignKeys0.FK_TRANSACTIONS_STAFF_1;
    public static final ForeignKey<Record, Record> FK_TRANSACTIONS_CUSTOMER_1 = ForeignKeys0.FK_TRANSACTIONS_CUSTOMER_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<Record, Integer> IDENTITY_CUSTOMER = createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.UID);
        public static Identity<Record, Integer> IDENTITY_STAFF = createIdentity(Staff.STAFF, Staff.STAFF.SID);
        public static Identity<Record, Integer> IDENTITY_TRANSACTIONS = createIdentity(Transactions.TRANSACTIONS, Transactions.TRANSACTIONS.TID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<Record> PK_CUSTOMER = createUniqueKey(Customer.CUSTOMER, "pk_Customer", Customer.CUSTOMER.UID);
        public static final UniqueKey<Record> PK_STAFF = createUniqueKey(Staff.STAFF, "pk_Staff", Staff.STAFF.SID);
        public static final UniqueKey<Record> PK_TRANSACTIONS = createUniqueKey(Transactions.TRANSACTIONS, "pk_Transactions", Transactions.TRANSACTIONS.TID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<Record, Record> FK_TRANSACTIONS_STAFF_1 = createForeignKey(org.comp3046.it9.Database.JooqGenerated.Keys.PK_STAFF, Transactions.TRANSACTIONS, "fk_Transactions_Staff_1", Transactions.TRANSACTIONS.STAFFID);
        public static final ForeignKey<Record, Record> FK_TRANSACTIONS_CUSTOMER_1 = createForeignKey(org.comp3046.it9.Database.JooqGenerated.Keys.PK_CUSTOMER, Transactions.TRANSACTIONS, "fk_Transactions_Customer_1", Transactions.TRANSACTIONS.CUSTOMERID);
    }
}
