/*
 * This file is generated by jOOQ.
*/
package org.comp3046.it9.Database.JooqGenerated;


import org.comp3046.it9.Database.JooqGenerated.tables.Customer;
import org.comp3046.it9.Database.JooqGenerated.tables.Movie;
import org.comp3046.it9.Database.JooqGenerated.tables.Staff;
import org.comp3046.it9.Database.JooqGenerated.tables.Transactions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>Customer</code>.
     */
    public static final Customer CUSTOMER = org.comp3046.it9.Database.JooqGenerated.tables.Customer.CUSTOMER;

    /**
     * The table <code>Movie</code>.
     */
    public static final Movie MOVIE = org.comp3046.it9.Database.JooqGenerated.tables.Movie.MOVIE;

    /**
     * The table <code>Staff</code>.
     */
    public static final Staff STAFF = org.comp3046.it9.Database.JooqGenerated.tables.Staff.STAFF;

    /**
     * The table <code>Transactions</code>.
     */
    public static final Transactions TRANSACTIONS = org.comp3046.it9.Database.JooqGenerated.tables.Transactions.TRANSACTIONS;
}
